### ISSUE TITLE
Plugin fails to load

### ISSUE THREAD

**Issue by echteFerux** [petko10/rhythmbox-plugin-playlists-import-export#12]
Hi, after installation I was able to see the plugin in Rhythmbox 3.3 on Ubuntu 16.04.

After activation I got an error. It said the following when I started Rhythmbox from command line:

I was actually able to fix this problem by removing ', Gconf' from both .py files.

I don't know whether this broke anything. I'm seeing 2 times 'import playlists' and 'export playlists'.

````
(rhythmbox:6005): libpeas-WARNING **: Error importing plugin 'playlists_ie':
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/filixandra/.local/share/rhythmbox/plugins/playlists_ie/playlists_ie.py", line 17, in <module>
    from playlists_ie_prefs import PlaylistsIOConfigureDialog
  File "/home/filixandra/.local/share/rhythmbox/plugins/playlists_ie/playlists_ie_prefs.py", line 15, in <module>
    from gi.repository import RB, Gtk, Gio, GObject, PeasGtk, GConf
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name GConf, introspection typelib not found
```
`

**Comment by petko10** [comment]
Just as a first thought: do you have the gconf package installed?

**Comment by echteFerux** [comment]
No idea. See attached images.

![schermafdruk van 2017-06-15 21-32-23](https://user-images.githubusercontent.com/7573012/27198570-0083c5ae-5213-11e7-97f3-0ac88a8dabce.png)
![schermafdruk van 2017-06-15 21-38-57](https://user-images.githubusercontent.com/7573012/27198575-0dafeec4-5213-11e7-92e2-31e4624f59d9.png)

**Comment by petko10** [comment]
Try installing the gconf2 and python-gconf packages. It's possible they solve the issue.

**Comment by petko10** [comment]
Closing due to inactivity. Do reopen if necessary .
