### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by eden-fed** [petko10/rhythmbox-plugin-playlists-import-export#8]
hello,
the plugin is not working in my computer,

this is the error message:

Traceback (most recent call last):
  File "/home/labuser/.local/share/rhythmbox/plugins/playlists_ie/playlists_ie.py", line 29, in do_activate
    app = shell.props.application
AttributeError: 'gi._gobject.GProps' object has no attribute 'application'

Traceback (most recent call last):
  File "/home/labuser/.local/share/rhythmbox/plugins/playlists_ie/playlists_ie.py", line 48, in do_deactivate
    app = shell.props.application
AttributeError: 'gi._gobject.GProps' object has no attribute 'application'

thanks

**Comment by petko10** [comment]
Closing due to inactivity. Do reopen the issue if necessary
